// 公共部分
export const CHANGE_THEME = 'CHANGE_THEME' // 设置主题
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE' // 设置语言
export const CHANGE_CONVERT_CURRENCY = 'CHANGE_CONVERT_CURRENCY' // 设置折算货币
export const CHANGE_SOCKET_REFRESH_STATUS = 'CHANGE_SOCKET_REFRESH_STATUS' // 改变socket刷新状态
export const CHANGE_SOCKET_DATA = 'CHANGE_SOCKET_DATA' // 改变socket数据
export const CHANGE_ACTIVE_SYMBOL = 'CHANGE_ACTIVE_SYMBOL' // 更改当前选中交易对
export const CHANGE_ACTIVE_TRADE_AREA = 'CHANGE_ACTIVE_TRADE_AREA' // 更改当前选中交易区
export const CHANGE_PALTE_LIST = 'CHANGE_PALTE_LIST' // 更改板块
export const CHANGE_CURRENCY_RATE_LIST = 'CHANGE_CURRENCY_RATE_LIST' // 更新当前汇率列表
export const CHANGE_ROUTER_PATH = 'CHANGE_ROUTER_PATH' // 路由跳转
// 个人中心 我的资产列表
export const USER_ASSETS_LIST = 'USER_ASSETS_LIST' // 我的资产列表
export const SET_COUNTRY_AREA_LIST = 'SET_COUNTRY_AREA_LIST' // 国家列表
export const USER_INFORMATION_REFRESH = 'USER_INFORMATION_REFRESH' // 用户信息刷新
