// 公共部分
export const CHANGE_THEME = 'CHANGE_THEME' // 设置主题
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE' // 设置语言
export const CHANGE_CONVERT_CURRENCY = 'CHANGE_CONVERT_CURRENCY' // 设置折算货币
// 首页
export const CHANGE_BANNER_BACKGROUND = 'CHANGE_BANNER_BACKGROUND' // 设置首页banner背景
export const CHANGE_COLLECT_LIST = 'CHANGE_COLLECT_LIST' // 设置收藏列表
export const CHANGE_COLLECT_STATUS_LIST = 'CHANGE_COLLECT_STATUS_LIST' // 设置收藏状态列表
// 币币交易
export const CHANGE_ACTIVE_SYMBOL = 'CHANGE_ACTIVE_SYMBOL' // 设置当前交易对
export const CHANGE_SOCKET_REFRESH_STATUS = 'CHANGE_SOCKET_REFRESH_STATUS' // 设置币币交易K线req请求刷新标识

// OTC交易
export const CHANGE_OTC_AVAILABLE_CURRENCY_NAME = 'CHANGE_OTC_AVAILABLE_CURRENCY_NAME' // OTC改变选中的可用币种名字
export const CHANGE_OTC_AVAILABLE_CURRENCY_ID = 'CHANGE_OTC_AVAILABLE_CURRENCY_ID' // OTC改变选中的可用币种id
// 投资理财
// 活动中心
// 个人中心
export const CHANGE_USER_CENTER_ACTIVE_NAME = 'CHANGE_USER_CENTER_ACTIVE_NAME' // 设置个人中心tab栏默认值
// 注册登录
