// OTC交易
// OTC改变选中的可用币种名字
export const CHANGE_OTC_AVAILABLE_CURRENCY_NAME = 'CHANGE_OTC_AVAILABLE_CURRENCY_NAME'
// OTC改变选中的可用币种id
export const CHANGE_OTC_AVAILABLE_CURRENCY_ID = 'CHANGE_OTC_AVAILABLE_CURRENCY_ID'
// OTC改变选中的可用币种小数位
export const CHANGE_OTC_AVAILABLE_CURRENCY_UNIT = 'CHANGE_OTC_AVAILABLE_CURRENCY_UNIT'
// OTC改变选中的可用币种partnerCoinId
// export const CHANGE_OTC_AVAILABLE_PARTNER_COIN_ID = 'CHANGE_OTC_AVAILABLE_PARTNER_COIN_ID'
// otc 商家和普通用户通用挂单页面可用币种起订量:选中不同的币种获得不同币种的起订量
export const CHANGE_OTC_MERCHANT_AND_COMMON_MINCOUNT = 'CHANGE_OTC_MERCHANT_AND_COMMON_MINCOUNT'
// otc 购买或者出售成功后跳转到交易中订单（首页的）的锚点地方
// export const CHANGE_OTC_ANCHOR_STATUS = 'CHANGE_OTC_ANCHOR_STATUS'
// 委托定单撤单后，更新首页挂单列表
export const UPDATE_OTC_HOME_LIST_STATUS = 'UPDATE_OTC_HOME_LIST_STATUS'
// 发布订单（商家和普通用户公用）后页面跳转到首页顶部状态
export const CHANGE_PUBLISH_ORDER_JUMP_TOP_STATUS = 'CHANGE_PUBLISH_ORDER_JUMP_TOP_STATUS'
// 普通用户点击otc导航弹窗提示点击申请按钮跳转到申请商家组件底部状态
export const CHANGE_OTC_APPLY_JUMP_BOTTOM_STATUS = 'CHANGE_OTC_APPLY_JUMP_BOTTOM_STATUS'
// 设置otc可用币种
export const SET_OTC_COIN_LIST_M = 'SET_OTC_COIN_LIST_M'
// otc主页国家列表筛选框选中的国家id
export const CHANGE_OTC_SELECTED_COUNTRY_ID = 'CHANGE_OTC_SELECTED_COUNTRY_ID'
// otc主页法币列表筛选框选中的法币类型id
export const CHANGE_OTC_SELECTED_CURRENCY_ID = 'CHANGE_OTC_SELECTED_CURRENCY_ID'
// 更改 及时通讯状态
export const UPDATE_IM_BOX_SHOW_STATUS_M = 'UPDATE_IM_BOX_SHOW_STATUS_M'
// 设置 OTC socket
export const UPDATE_IM_SOCKET_M = 'UPDATE_IM_SOCKET_M'
export const UPDATE_IM_HAS_NEW_MESSAGE_MAP_M = 'UPDATE_IM_HAS_NEW_MESSAGE_MAP_M'
// 改变商家信息页面拉黑成功后调转到个人中心拉黑tab栏状态
export const CHANGE_BLACK_TABS_STATUS_M = 'CHANGE_BLACK_TABS_STATUS_M'
// 更新OTCIM
export const UPDATE_OTC_IM_SOCKET_STATUS_M = 'UPDATE_OTC_IM_SOCKET_STATUS_M'
// 更新 OTCIM 心跳状态状态
export const UPDATE_OTC_IM_SOCKET_HEART_M = 'UPDATE_OTC_IM_SOCKET_HEART_M'
// 更新OTC最新消息
export const UPDATE_NEW_IM_MESSAGE_M = 'UPDATE_NEW_IM_MESSAGE_M'
