// OTC交易
// OTC改变选中的可用币种名字
export const CHANGE_OTC_AVAILABLE_CURRENCY_NAME = 'CHANGE_OTC_AVAILABLE_CURRENCY_NAME'
// OTC改变选中的可用币种id
export const CHANGE_OTC_AVAILABLE_CURRENCY_ID = 'CHANGE_OTC_AVAILABLE_CURRENCY_ID'
