// OTC交易
// OTC改变选中的可用币种名字
export const CHANGE_OTC_AVAILABLE_CURRENCY_NAME = 'CHANGE_OTC_AVAILABLE_CURRENCY_NAME'
// OTC改变选中的可用币种id
export const CHANGE_OTC_AVAILABLE_CURRENCY_ID = 'CHANGE_OTC_AVAILABLE_CURRENCY_ID'
// OTC改变选中的可用币种partnerCoinId
export const CHANGE_OTC_AVAILABLE_PARTNER_COIN_ID = 'CHANGE_OTC_AVAILABLE_PARTNER_COIN_ID'
// otc 商家和普通用户通用挂单页面可用币种起订量:选中不同的币种获得不同币种的起订量
export const CHANGE_OTC_MERCHANT_AND_COMMON_MINCOUNT = 'CHANGE_OTC_MERCHANT_AND_COMMON_MINCOUNT'
// otc 购买或者出售成功后跳转到交易中订单（首页的）的锚点地方
export const CHANGE_OTC_ANCHOR_STATUS = 'CHANGE_OTC_ANCHOR_STATUS'
// 委托定单撤单后，更新首页挂单列表
export const UPDATE_OTC_HOME_LIST_STATUS = 'UPDATE_OTC_HOME_LIST_STATUS'
// 发布订单（商家和普通用户公用）后页面跳转到首页顶部状态
export const CHANGE_PUBLISH_ORDER_JUMP_TOP_STATUS = 'CHANGE_PUBLISH_ORDER_JUMP_TOP_STATUS'
// 普通用户点击otc导航弹窗提示点击申请按钮跳转到申请商家组件底部状态
export const CHANGE_OTC_APPLY_JUMP_BOTTOM_STATUS = 'CHANGE_OTC_APPLY_JUMP_BOTTOM_STATUS'
// 设置otc可用币种
export const SET_OTC_COIN_LIST_M = 'SET_OTC_COIN_LIST_M'
