
export const FINANCE_LINE_SELECT_COIDINFOR = 'FINANCE_LINE_SELECT_COIDINFOR' // 设置投资理财线形图数据
export const FINANCE_PIE_INVESTMENT_VALUE = 'FINANCE_PIE_INVESTMENT_VALUE' // 饼状图数据1
export const FINANCE_PIE_GET_MONEY_VALUE = 'FINANCE_PIE_INVESTMENT_VALUE' // 饼状图数据二
