// 首页
export const CHANGE_BANNER_BACKGROUND = 'CHANGE_BANNER_BACKGROUND' // 设置首页banner背景
export const CHANGE_BANNER_ACTIVE = 'CHANGE_BANNER_ACTIVE' //
export const CHANGE_COLLECT_LIST = 'CHANGE_COLLECT_LIST' // 设置收藏列表
export const CHANGE_COLLECT_STATUS_LIST = 'CHANGE_COLLECT_STATUS_LIST' // 设置收藏状态列表
