// 首页
export const CHANGE_BANNER_BACKGROUND = 'CHANGE_BANNER_BACKGROUND' // 设置首页banner背景
export const CHANGE_BANNER_ACTIVE = 'CHANGE_BANNER_ACTIVE' //
export const CHANGE_COLLECT_SYMBOL = 'CHANGE_COLLECT_SYMBOL' // 增加、删除收藏列表
export const CHANGE_SYMBOL_MAP = 'CHANGE_SYMBOL_MAP' // 设置交易对映射
