// 个人中心
export const CHANGE_USER_CENTER_ACTIVE_NAME = 'CHANGE_USER_CENTER_ACTIVE_NAME' // 设置个人中心tab栏默认值
export const CHANGE_REF_SECURITY_CENTER_INFO = 'CHANGE_REF_SECURITY_CENTER_INFO' // 安全中心状态
export const CHANGE_REF_ACCOUNT_CREDITED_STATE = 'CHANGE_REF_ACCOUNT_CREDITED_STATE' // 收款方式
