// 个人中心
export const CHANGE_USER_CENTER_ACTIVE_NAME = 'CHANGE_USER_CENTER_ACTIVE_NAME' // 设置个人中心tab栏默认值
export const CHANGE_REF_SECURITY_CENTER_INFO = 'CHANGE_REF_SECURITY_CENTER_INFO' // 安全中心状态
export const CHANGE_REF_ACCOUNT_CREDITED_STATE = 'CHANGE_REF_ACCOUNT_CREDITED_STATE' // 收款方式
// 安全中心状态
export const GET_SECURITY_CENTER = 'GET_SECURITY_CENTER'
// 获取法币交易页面数据
export const SET_LEGAL_TENDER_LIST = 'SET_LEGAL_TENDER_LIST'
// 获取交易中的订单
export const CHANGE_MERCHANTS_ORDERS_LIST = 'CHANGE_MERCHANTS_ORDERS_LIST'
// 获取已完成的订单
export const CHANGE_COMPLETED_ORDERS_LIST = 'CHANGE_COMPLETED_ORDERS_LIST'
// 获取已取消的订单
export const CHANGE_CANCELED_ORDERS_LIST = 'CHANGE_CANCELED_ORDERS_LIST'
// 获取冻结中的订单
export const CHANGE_FROZEN_ORDERS_LIST = 'CHANGE_FROZEN_ORDERS_LIST'
// 获取委托订单
export const CHANGE_ENTRUST_ORDERS_LIST = 'CHANGE_ENTRUST_ORDERS_LIST'
// 法币交易各个列表刷新状态
export const SET_LEGAL_TENDER_REFLASH_STATUS = 'SET_LEGAL_TENDER_REFLASH_STATUS'
// 更改分页页码
export const CHANGE_LEGAL_PAGE = 'CHANGE_LEGAL_PAGE'
// 更改重新渲染交易中订单列表状态
export const CHANGE_RE_RENDER_TRADING_LIST_STATUS = 'CHANGE_RE_RENDER_TRADING_LIST_STATUS'
