// 个人中心
export const CHANGE_USER_CENTER_ACTIVE_NAME = 'CHANGE_USER_CENTER_ACTIVE_NAME' // 设置个人中心tab栏默认值
export const CHANGE_REF_SECURITY_CENTER_INFO = 'CHANGE_REF_SECURITY_CENTER_INFO' // 安全中心状态
export const CHANGE_REF_ACCOUNT_CREDITED_STATE = 'CHANGE_REF_ACCOUNT_CREDITED_STATE' // 收款方式
// 安全中心状态
export const GET_SECURITY_CENTER = 'GET_SECURITY_CENTER'
// 获取法币交易页面数据
export const SET_LEGAL_TENDER_LIST = 'SET_LEGAL_TENDER_LIST'
// 获取交易中的订单
export const CHANGE_MERCHANTS_ORDERS_LIST = 'CHANGE_MERCHANTS_ORDERS_LIST'
// 获取已完成的订单
export const CHANGE_COMPLETED_ORDERS_LIST = 'CHANGE_COMPLETED_ORDERS_LIST'
// 获取已取消的订单
export const CHANGE_CANCELED_ORDERS_LIST = 'CHANGE_CANCELED_ORDERS_LIST'
// 获取冻结中的订单
export const CHANGE_FROZEN_ORDERS_LIST = 'CHANGE_FROZEN_ORDERS_LIST'
// 获取委托订单
export const CHANGE_ENTRUST_ORDERS_LIST = 'CHANGE_ENTRUST_ORDERS_LIST'
// 法币交易各个列表刷新状态
export const SET_LEGAL_TENDER_REFLASH_STATUS = 'SET_LEGAL_TENDER_REFLASH_STATUS'
// 更改分页页码
export const CHANGE_LEGAL_PAGE = 'CHANGE_LEGAL_PAGE'
// 更改重新渲染交易中订单列表状态
export const CHANGE_RE_RENDER_TRADING_LIST_STATUS = 'CHANGE_RE_RENDER_TRADING_LIST_STATUS'
// 设置跳转到新增币种的地址
export const SET_NEW_WITHDRAW_ADDRESS = 'SET_NEW_WITHDRAW_ADDRESS'
// 我的资产跳转到账单明细提币
export const SET_NEW_WITHDRAW_RECORD = 'SET_NEW_WITHDRAW_RECORD'
// 我的资产跳转到账单明细提币携带提币充值类型
export const SET_NEW_WITHDRAW_RECORD_STATUS = 'SET_NEW_WITHDRAW_RECORD_STATUS'
// 更新全局链名称
export const UPDATE_ACTIVE_LINK_NAMES_M = 'UPDATE_ACTIVE_LINK_NAMES_M'
// 更新全局链名称
export const UPDATE_LINK_NAMES_M = 'UPDATE_LINK_NAMES_M'
// 改变清除交易中数据方法的状态
export const CHANGE_CLEAR_DATA_STATUS_M = 'CHANGE_CLEAR_DATA_STATUS_M'
// 改变是否重新刷新个人中心个人资产列表状态
export const CHANGE_REFRESH_PERSONAL_ASSETS_LIST_STATUS_M = 'CHANGE_REFRESH_PERSONAL_ASSETS_LIST_STATUS_M'
