export const TOGGLE_REFRESH_ENTRUST_LIST_STATUS = 'TOGGLE_REFRESH_ENTRUST_LIST_STATUS' // 切换委托列表刷新状态
export const CHANGE_ACTIVE_TAB_ID = 'CHANGE_ACTIVE_TAB_ID' // 切换币币交易当前选中交易区id
export const CHANGE_ACTIVE_PRICE_ITEM = 'CHANGE_ACTIVE_PRICE_ITEM' // 改变用户选中买卖价格
